---
services:
  ocv-backend:
    container_name: ocv-backend
    build: .
    environment:
      # DB container_name used for the database connection in /config/databasePool.ts
      - DB_HOST=ocv-postgres
    ports:
      - 3001:3000
    networks:
      - ocv-network
    restart: unless-stopped

networks:
  ocv-network:
    external: true
